version: '3.8'
services:
  nginx-1:
    container_name: nginx-1
    build: ./debian-python
    tty: true    
    ports:
      - 8080:80
  nginx-2:
    container_name: nginx-2
    build: ./debian-python
    tty: true
    ports:
      - 8081:80
  prometheus:
    container_name: prometheus
    image: prom/prometheus:v2.40.3
    ports:
      - "9090:9090"
