version: '3.8'
services:
  nginx-1:
    container_name: nginx-1
    build: ./debian-python
    tty: true    
    ports:
      - 8080:80
  nginx-2:
    container_name: nginx-2
    build: ./debian-python
    tty: true
    ports:
      - 8081:80
